
const AGE_KEY='msfk-age';
const WELCOME_KEY='msfk-welcome-dismissed';
const allowed=['preschool','elementary','middle','high'];
function setAge(age){
 if(!allowed.includes(age)) age='elementary';
 localStorage.setItem(AGE_KEY,age);
 document.querySelectorAll('.age-pill').forEach(b=>b.classList.toggle('active',b.dataset.age===age));
 document.querySelectorAll('[data-age-copy]').forEach(el=>el.classList.toggle('active',el.dataset.ageCopy===age));
 document.querySelectorAll('.current-age-label').forEach(el=>el.textContent=({'preschool':'Preschool','elementary':'Elementary School','middle':'Middle School','high':'High School'})[age]);
 const select=document.querySelector('#agePreference'); if(select) select.value=age;
}
function applyPublicCopy(){
 const about=document.querySelector('article.about');
 if(about){
   about.innerHTML=`
      <h1>Why does this exist?</h1>
      <p>I read Money Stuff. I also have a baby.</p>
      <p>At some point I found myself reading Matt Levine’s explanations of derivatives, prediction markets and questionable corporate behavior out loud to my 9-month-old daughter, who was naturally following all of it very closely.</p>
      <p>So I made this.</p>
      <p>Money Stuff for Kids uses AI to turn stories from Money Stuff into little picture-book versions.</p>
      <p><strong>This is an unofficial project. It is not affiliated with or endorsed by Bloomberg, Matt Levine, or Money Stuff.</strong> The retellings and illustrations are generated by AI and will contain mistakes. Obviously, nothing here is financial, legal or investment advice.</p>
      <p>More importantly: this is no substitute for Money Stuff. You should read that instead.</p>
      <p><a class="about-cta" href="https://www.bloomberg.com/account/newsletters/money-stuff" target="_blank" rel="noopener">Subscribe to Money Stuff ↗</a></p>`;
 }
 const modal=document.querySelector('#welcomeModal');
 if(modal){
   const card=modal.querySelector('.welcome-card');
   card.innerHTML=`
        <h2 id="welcomeTitle">A very unofficial Money Stuff project</h2>
        <p><strong>This is not affiliated with or endorsed by Bloomberg, Matt Levine, or Money Stuff.</strong></p>
        <p>I made it after reading enough Money Stuff to my 9-month-old daughter that I decided she needed her own version.</p>
        <p>Everything here is AI-generated based on real Money Stuff stories, but there are absolutely mistakes. Obviously nothing here is legal, financial, or investment advice.</p>
        <p>If you don’t already read the real Money Stuff, you should. It's great.</p>
        <button type="button" class="welcome-dismiss">Got it</button>
        <div class="welcome-links">
          <a href="https://www.bloomberg.com/account/newsletters/money-stuff" target="_blank" rel="noopener">Read the real Money Stuff ↗</a>
          <a href="https://linkedin.com/in/brettandler" target="_blank" rel="noopener">Who made this? ↗</a>
        </div>`;
 }
}
document.addEventListener('DOMContentLoaded',()=>{
 applyPublicCopy();
 const modal=document.querySelector('#welcomeModal');
 if(modal){
   let dismissed=false;
   try{dismissed=localStorage.getItem(WELCOME_KEY)==='true'}catch(error){}
   if(!dismissed){
     modal.hidden=false;
     document.body.classList.add('modal-open');
     const button=modal.querySelector('.welcome-dismiss');
     const dismiss=()=>{
       try{localStorage.setItem(WELCOME_KEY,'true')}catch(error){}
       modal.hidden=true;
       document.body.classList.remove('modal-open');
     };
     button.addEventListener('click',dismiss);
     document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)dismiss()});
     button.focus();
   }
 }
 const multiAge=document.body.dataset.publicAgeMode==='multi';
 if(multiAge){
   setAge(localStorage.getItem(AGE_KEY)||'elementary');
   document.querySelectorAll('.age-pill').forEach(b=>b.addEventListener('click',()=>setAge(b.dataset.age)));
 }
 const form=document.querySelector('#signupForm');
 if(form){
   form.addEventListener('submit',async(e)=>{
     e.preventDefault();
     const status=document.querySelector('#signupStatus'); status.textContent='Signing you up…';
     const fd=new FormData(form);
     try{
       const r=await fetch('https://formsubmit.co/ajax/brettaiinbox@gmail.com',{method:'POST',headers:{'Accept':'application/json'},body:fd});
       const j=await r.json();
       if(!r.ok) throw new Error(j.message||'Unable to subscribe');
       status.textContent='Check your inbox — you’re on the list.';
       form.reset(); if(multiAge) setAge(localStorage.getItem(AGE_KEY)||'elementary');
     }catch(err){status.textContent='Signup did not go through. Please try again.'}
   })
 }
});
